export const AppColors = {
  brand: {
    primary: '#2B8EF0',
    primaryStrong: '#1D4ED8',
    primarySoft: '#EBF5FF',
    primaryBorder: '#BFDBFE',
    secondary: '#3B82F6',
    accent: '#22C55E',
  },
  text: {
    primary: '#111827',
    secondary: '#374151',
    tertiary: '#6B7280',
    muted: '#9CA3AF',
    inverse: '#FFFFFF',
  },
  surface: {
    base: '#FFFFFF',
    page: '#F8FAFC',
    muted: '#F3F4F6',
    subtle: '#F1F5F9',
  },
  border: {
    default: '#E5E7EB',
    soft: '#D1D5DB',
    strong: '#94A3B8',
  },
  status: {
    success: '#22C55E',
    successSoft: '#DCFCE7',
    successStrong: '#16A34A',
    warning: '#F59E0B',
    warningSoft: '#FEF3C7',
    warningStrong: '#D97706',
    danger: '#EF4444',
    dangerSoft: '#FEE2E2',
    dangerStrong: '#DC2626',
    info: '#3B82F6',
    infoSoft: '#DBEAFE',
    infoStrong: '#1E3A8A',
  },
  map: {
    start: '#0EA5E9',
    pin: '#10B981',
    route: '#3B82F6',
    timeline: '#BFDBFE',
  },
} as const;

export const IconColors = {
  active: AppColors.brand.primary,
  inactive: AppColors.text.muted,
  neutral: AppColors.text.secondary,
  success: AppColors.status.success,
  warning: AppColors.status.warning,
  danger: AppColors.status.danger,
  info: AppColors.status.info,
  mapStart: AppColors.map.start,
  mapPin: AppColors.map.pin,
} as const;

export const LegacyColorMap: Record<string, string> = {
  '#2396EC': AppColors.brand.primary,
  '#1F9CFF': AppColors.brand.primary,
  '#2563EB': AppColors.brand.secondary,
  '#0369A1': AppColors.brand.primaryStrong,
  '#60A5FA': AppColors.brand.secondary,
  '#E7F3FF': AppColors.brand.primarySoft,
  '#E9F4FF': AppColors.brand.primarySoft,
  '#D1E6FF': AppColors.brand.primarySoft,
  '#C7DEFF': AppColors.brand.primaryBorder,
  '#93C5FD': AppColors.brand.primaryBorder,
  '#F5F6FA': AppColors.surface.page,
  '#F9FAFB': AppColors.surface.page,
  '#4B5563': AppColors.text.secondary,
  '#1F2937': AppColors.text.primary,
  '#1E293B': AppColors.text.primary,
  '#059669': AppColors.status.successStrong,
  '#FDE7B0': AppColors.status.warningSoft,
  '#E2E8F0': AppColors.border.default,
  '#64748B': AppColors.text.tertiary,
  '#DCFCE7': AppColors.status.successSoft,
};
